batch_size: 32
client_dynamism:
  fast:
    participation_rate: 0.9
    proportion: 0.3
  normal:
    participation_rate: 0.7
    proportion: 0.5
  slow:
    participation_rate: 0.5
    proportion: 0.2
client_types:
  medium:
    computational_power: 0.7
    network_speed: 0.7
    proportion: 0.5
  strong:
    computational_power: 1
    network_speed: 1
    proportion: 0.3
  weak:
    computational_power: 0.4
    network_speed: 0.5
    proportion: 0.2
dataset_name: mnist
datasets:
- input_shape:
  - 28
  - 28
  - 1
  name: mnist
  num_classes: 10
- input_shape:
  - 28
  - 28
  - 1
  name: fashion_mnist
  num_classes: 10
- input_shape:
  - 32
  - 32
  - 3
  name: cifar10
  num_classes: 10
- input_shape:
  - 32
  - 32
  - 3
  name: cifar100
  num_classes: 100
- input_shape:
  - 32
  - 32
  - 3
  name: svhn
  num_classes: 10
- input_shape:
  - 150
  - 150
  - 3
  name: chest_xray
  num_classes: 2
- input_shape:
  - 224
  - 224
  - 3
  name: isic
  num_classes: 9
- input_shape:
  - 224
  - 224
  - 3
  name: brain_tumor
  num_classes: 4
- input_shape:
  - 224
  - 224
  - 3
  name: brain_tumor_mri
  num_classes: 4
- input_shape:
  - 224
  - 224
  - 3
  name: retinopathy
  num_classes: 5
- input_shape:
  - 224
  - 224
  - 3
  name: skin_cancer
  num_classes: 2
global_epochs: 2
global_participation_rate: 1.0
learning_rate: 0.001
local_epochs: 1
mu: 0.1
nodes:
- city: Genoa
  client_type: strong
  dynamism_type: fast
  id: 1
  latitude: 44.4056
  longitude: 8.9463
  name: "Charit\xE9 Universit\xE4tsmedizin"
- city: Potenza
  client_type: strong
  dynamism_type: fast
  id: 2
  latitude: 40.6404
  longitude: 15.8056
  name: "AP-HP H\xF4pital Saint-Louis"
- city: Florence
  client_type: strong
  dynamism_type: fast
  id: 3
  latitude: 43.7696
  longitude: 11.2558
  name: NHS Royal London Hospital
- city: Delhi
  client_type: strong
  dynamism_type: fast
  id: 4
  latitude: 28.7041
  longitude: 77.1025
  name: Istituto Europeo di Oncologia
- city: Mumbai
  client_type: medium
  dynamism_type: normal
  id: 5
  latitude: 19.076
  longitude: 72.8777
  name: Hospital 12 de Octubre
- city: Vancouver
  client_type: medium
  dynamism_type: normal
  id: 6
  latitude: 49.2827
  longitude: -123.1207
  name: Amsterdam UMC
- city: Hong Kong
  client_type: medium
  dynamism_type: normal
  id: 7
  latitude: 22.3193
  longitude: 114.1694
  name: Karolinska Universitetssjukhuset
- city: Melbourne
  client_type: medium
  dynamism_type: normal
  id: 8
  latitude: -37.8136
  longitude: 144.9631
  name: "AKH Wien \u2013 Univ. Dermatologie"
- city: Johannesburg
  client_type: weak
  dynamism_type: normal
  id: 9
  latitude: -26.2041
  longitude: 28.0473
  name: "Universit\xE4tsspital Z\xFCrich"
- city: Bologna
  client_type: weak
  dynamism_type: slow
  id: 10
  latitude: 44.4949
  longitude: 11.3426
  name: Hospital de Santa Maria
- city: Singapore
  client_type: weak
  dynamism_type: slow
  id: 11
  latitude: 1.3521
  longitude: 103.8198
  name: ATTIKON University Hospital
- city: Tokyo
  client_type: weak
  dynamism_type: slow
  id: 12
  latitude: 35.6762
  longitude: 139.6503
  name: Centralny Szpital Kliniczny
num_clients: 5
ts: 5
